//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_tests.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model_Layer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_tests.ServiceReference1.InternalInfoUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_tests.ServiceReference1.ExternalInfoUser))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Location_DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid User_GuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location_Data {
            get {
                return this.Location_DataField;
            }
            set {
                if ((object.ReferenceEquals(this.Location_DataField, value) != true)) {
                    this.Location_DataField = value;
                    this.RaisePropertyChanged("Location_Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid User_Guid {
            get {
                return this.User_GuidField;
            }
            set {
                if ((this.User_GuidField.Equals(value) != true)) {
                    this.User_GuidField = value;
                    this.RaisePropertyChanged("User_Guid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalInfoUser", Namespace="http://schemas.datacontract.org/2004/07/Model_Layer")]
    [System.SerializableAttribute()]
    public partial class InternalInfoUser : WCF_tests.ServiceReference1.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalInfoUser", Namespace="http://schemas.datacontract.org/2004/07/Model_Layer")]
    [System.SerializableAttribute()]
    public partial class ExternalInfoUser : WCF_tests.ServiceReference1.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Account_ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_LoginField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Account_Active {
            get {
                return this.Account_ActiveField;
            }
            set {
                if ((this.Account_ActiveField.Equals(value) != true)) {
                    this.Account_ActiveField = value;
                    this.RaisePropertyChanged("Account_Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Login {
            get {
                return this.Last_LoginField;
            }
            set {
                if ((this.Last_LoginField.Equals(value) != true)) {
                    this.Last_LoginField = value;
                    this.RaisePropertyChanged("Last_Login");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        bool Create(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        bool Update(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Disable", ReplyAction="http://tempuri.org/IUserService/DisableResponse")]
        bool Disable(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Disable", ReplyAction="http://tempuri.org/IUserService/DisableResponse")]
        System.Threading.Tasks.Task<bool> DisableAsync(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/BlockUser", ReplyAction="http://tempuri.org/IUserService/BlockUserResponse")]
        bool BlockUser(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/BlockUser", ReplyAction="http://tempuri.org/IUserService/BlockUserResponse")]
        System.Threading.Tasks.Task<bool> BlockUserAsync(WCF_tests.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetMatchedUsers", ReplyAction="http://tempuri.org/IUserService/GetMatchedUsersResponse")]
        WCF_tests.ServiceReference1.User[] GetMatchedUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetMatchedUsers", ReplyAction="http://tempuri.org/IUserService/GetMatchedUsersResponse")]
        System.Threading.Tasks.Task<WCF_tests.ServiceReference1.User[]> GetMatchedUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : WCF_tests.ServiceReference1.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<WCF_tests.ServiceReference1.IUserService>, WCF_tests.ServiceReference1.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(WCF_tests.ServiceReference1.User user) {
            return base.Channel.Create(user);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(WCF_tests.ServiceReference1.User user) {
            return base.Channel.CreateAsync(user);
        }
        
        public bool Update(WCF_tests.ServiceReference1.User user) {
            return base.Channel.Update(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(WCF_tests.ServiceReference1.User user) {
            return base.Channel.UpdateAsync(user);
        }
        
        public bool Disable(WCF_tests.ServiceReference1.User user) {
            return base.Channel.Disable(user);
        }
        
        public System.Threading.Tasks.Task<bool> DisableAsync(WCF_tests.ServiceReference1.User user) {
            return base.Channel.DisableAsync(user);
        }
        
        public bool BlockUser(WCF_tests.ServiceReference1.User user) {
            return base.Channel.BlockUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> BlockUserAsync(WCF_tests.ServiceReference1.User user) {
            return base.Channel.BlockUserAsync(user);
        }
        
        public WCF_tests.ServiceReference1.User[] GetMatchedUsers() {
            return base.Channel.GetMatchedUsers();
        }
        
        public System.Threading.Tasks.Task<WCF_tests.ServiceReference1.User[]> GetMatchedUsersAsync() {
            return base.Channel.GetMatchedUsersAsync();
        }
    }
}
